site_name: Kilpakävelyn liittotuomarikoulutus
theme: 
  name: material
  language: fi
  features:
  - search.suggest
  - search.highlight
nav:
  - 'Tuomitseva tuomari': 'tuomari_kertaus.md'
  - 'Ylituomari': 'ylituomari.md'
  - 'Ylituomarin toimintaohjeita': 'ylituomarin_toiminta.md'
  - 'Muita sääntöjä': 'muita_saantoja.md'
  - 'Kilpailujärjestelyt': 'kilpailujarjestelyt.md'
  - 'Videoharjoituksia': 'videoharjoituksia.md'
  - 'Säännöt 2024': 'saannot.md'
plugins:
  - search
  - autorefs
  - glightbox
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
